version: "3"
services:
  nats:
    image: nats:2.3.1
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
  wasmcloud_host:
    image: wasmcloud-host:apktest2
    # image: wasmcloud-host:0.20.0
    depends_on:
      - nats
    ports:
      - "4000:4000"
