version: "3"
services:
  nats:
    image: nats:2.3.1
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
  redis:
    image: redis:6.2.4
    ports:
      - "6379:6379"
  wasmcloud_host:
    image: "${WASMCLOUD_HOST_IMAGE}"
    depends_on:
      - nats
    ports:
      - "4000:4000"
      - "8080:8080"
